#ifndef MCAL_INTERRUPT_CONFIG_H
#define	MCAL_INTERRUPT_CONFIG_H

#include "../mcal_std_types.h"
#include "../GPIO/hal_gpio.h"


#define INTERRUPT_ENABLE                            1
#define INTERRUPT_DISABLE                           0
#define INTERRUPT_OCCUR                             1
#define INTERRUPT_NOT_OCCUR                         0
#define INTERRUPT_PRIORITY_ENABLE                   1
#define INTERRUPT_PRIORITY_DISABLE                  0

#define INTERRUPT_FEATURE_ENABLE                    1
#define INTERRUPT_PRIORITY_LEVELS_ENABLE            INTERRUPT_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_INTx_FEATURE_ENABLE      INTERRUPT_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_ON_CHANGE_FEATURE_ENABLE INTERRUPT_FEATURE_ENABLE
#define ADC_INTERRUPT_FEATURE_ENABLE                INTERRUPT_FEATURE_ENABLE
#define TImer0_INTERRUPT_FEATURE_ENABLE             INTERRUPT_FEATURE_ENABLE
#define TImer1_INTERRUPT_FEATURE_ENABLE             INTERRUPT_FEATURE_ENABLE
#define TImer2_INTERRUPT_FEATURE_ENABLE             INTERRUPT_FEATURE_ENABLE
#define TImer3_INTERRUPT_FEATURE_ENABLE             INTERRUPT_FEATURE_ENABLE
#define CCP1_INTERRUPT_FEATURE_ENABLE               INTERRUPT_FEATURE_ENABLE
//#define CCP2_INTERRUPT_FEATURE_ENABLE               INTERRUPT_FEATURE_ENABLE
#define EUSART_INTERRUPT_FEATURE_ENABLE_TX          INTERRUPT_FEATURE_ENABLE
#define EUSART_INTERRUPT_FEATURE_ENABLE_RX          INTERRUPT_FEATURE_ENABLE
#define MSSP_I2C_INTERRUPT_FEATURE_ENABLE           INTERRUPT_FEATURE_ENABLE

#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE

#define INTERRUPT_GLOBAL_INTERRUPT_HIGH_ENABLE()    (INTCONbits.GIEH = 1)
#define INTERRUPT_GLOBAL_INTERRUPT_HIGH_DISABLE()   (INTCONbits.GIEH = 0)

#define INTERRUPT_GLOBAL_INTERRUPT_LOW_ENABLE()     (INTCONbits.GIEL = 1)
#define INTERRUPT_GLOBAL_INTERRUPT_LOW_DISABLE()    (INTCONbits.GIEL = 0)

#define INTERRUPT_PRIORITY_LEVEL_ENABLE()           (RCONbits.IPEN = 1)
#define INTERRUPT_PRIORITY_LEVEL_DISABLE()          (RCONbits.IPEN = 0)

#else

#define INTERRUPT_PERIPHERAL_INTERRUPT_ENABLE()  (INTCONbits.PEIE = 1)
#define INTERRUPT_PERIPHERAL_INTERRUPT_DISABLE() (INTCONbits.PEIE = 0)

#define INTERRUPT_GLOBAL_INTERRUPT_ENABLE()      (INTCONbits.GIE = 1)
#define INTERRUPT_GLOBAL_INTERRUPT_DISABLE()     (INTCONbits.GIE = 0)

#endif

typedef enum
{
    LOW_PRIORITY,
    HIGH_PRIORITY      
}INTERRUPT_PRIORITY_CFG;

#endif	/* MCAL_INTERRUPT_CONFIG_H */